In [1]:
import numpy as np

In [2]:
array_a = np.array([1,2,3])

In [5]:
print(array_a)

[1 2 3]


In [4]:
type(array_a)

numpy.ndarray

In [6]:
array_a.shape

(3,)

In [7]:
array_b = np.array([[7,8,9],[10,11,12]])

In [8]:
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
print(array_b)

[[ 7  8  9]
 [10 11 12]]


In [10]:
type(array_b)

numpy.ndarray

In [11]:
array_b.shape

(2, 3)

In [12]:
array_b.shape[1]

3

In [13]:
array_c = np.array(13)

In [14]:
array_c

array(13)

In [15]:
type(array_c)

numpy.ndarray

In [16]:
print(array_c)

13


In [17]:
array_c.shape

()

In [18]:
array_d = np.array([15])

In [19]:
array_d

array([15])

In [20]:
print(array_d)

[15]


In [21]:
array_d.shape

(1,)

In [22]:
array_e = np.array([[15]])

In [23]:
array_e

array([[15]])

In [24]:
type(array_e)

numpy.ndarray

In [28]:
list_a = [[1,2,3],[4,5,6]]

In [29]:
len(list_a)

2

In [30]:
array_a = np.array(list_a)

In [31]:
type(list_a)

list

In [32]:
type(array_a)

numpy.ndarray

In [33]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [34]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [35]:
array_a.shape

(2, 3)

In [36]:
np.sqrt(list_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
np.sqrt(list_a[1,0])

TypeError: list indices must be integers or slices, not tuple