# NumPy DataTypes

In [1]:
import numpy as np

### 1. With the help of the <i> np.array() </i>function, create a 1-D array variable <i> array_hw_1 </i> with the numbers from 1 to 8 and display it on the screen.

In [5]:
array_hw_1 = np.array([1,2,3,4,5,6,7,8])
array_hw_1

array([1, 2, 3, 4, 5, 6, 7, 8])

### 2.Check its type, shape and size. 
<i> (<b>Hint </b>: "type" is a Python function, while "shape" and "size" are attributes of the array) </i>

In [6]:
type(array_hw_1)

numpy.ndarray

In [7]:
array_hw_1.size

8

In [8]:
array_hw_1.shape

(8,)

### 3. Now, create a 2x4 2-D array, <i> array_hw_2</i> with the same values & display it on screen. 

In [10]:
array_hw_2 =np.array([[1,2,3,4],[5,6,7,8]])
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 4. Find its type, shape, and size. 

In [12]:
type(array_hw_2)

numpy.ndarray

In [13]:
array_hw_2.shape

(2, 4)

In [14]:
array_hw_2.size

8

### 5. Use square brackets to create a 3-D array with the same values as <i> array_hw_2 </i> and display it on screen.

In [19]:
array_hw_3 = np.array([[1,2,3,4],[5,6,7,8]])
array_hw_3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 6. Find its type, shape and size. 


In [20]:
type(array_hw_3)

numpy.ndarray

In [21]:
array_hw_3.shape

(2, 4)

In [22]:
array_hw_3.size

8

### 7. Define a 2-D list <i> list_hw_1 </i> with the same values as <i> array_hw_2 </i>and display it on screen.

In [24]:
list_hw_1 = [[1,2,3,4],[5,6,7,8]]
list_hw_1

[[1, 2, 3, 4], [5, 6, 7, 8]]

### 8. Find the length of this 2-D list. 

In [25]:
len(list_hw_1)

2

### 9. Fint the length of one of its sublists. 

In [26]:
len(list_hw_1[0])

4

### 10. Verify its type. 

In [27]:
type(list_hw_1[0])

list

### 11. Use the <i>np.array()</i> function to create an array out of <i> list_hw_1</i> and display it on screen.

In [28]:
array = np.array(list_hw_1)
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 12. Create two more variables and display them on screen:
    A) A list which is the sum of the two sublists of list_hw_1;
    B) An array which is the sum of the two subarrays of array_hw_4;
    
    (Hint: Use indexing to refer to the different sub-lists/arrays)

In [32]:
listSum = list_hw_1[0] + list_hw_1[1]

In [33]:
arraySum = array[0] + array[1]

In [34]:
listSum

[1, 2, 3, 4, 5, 6, 7, 8]

In [35]:
arraySum

array([ 6,  8, 10, 12])

### 13. Find the square roots of all the elements in <i> array_sum </i>
   <i> (<b>Hint</b>: Use the np.sqrt() function)

In [36]:
np.sqrt(arraySum)

array([2.44948974, 2.82842712, 3.16227766, 3.46410162])

### 13. Find the square roots of all the elements in <i> list_sum </i>
   <i> (<b>Hint</b>: Most NumPy functions are equipped to handle <b> lists </b>like ndarrays with the same shape)

In [37]:
np.sqrt(listSum)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

### 14. Use <i> np.genfromtxt() </i> to import the <i> "Lending-Company-Total-Price.csv" </i> file as strings and display its contents.
    You can open the file in a text editor like Notepad++ to check its delimiter. 

In [38]:
lending_co_total = np.genfromtxt("Lending-Company-Total-Price.csv", delimiter = ",")
lending_co_total

array([[      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       [1.000e+00,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       [2.000e+00,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       ...,
       [4.130e+02,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       [4.140e+02,       nan,       nan, ...,       nan,       nan,
        1.560e+04],
       [4.150e+02,       nan,       nan, ...,       nan,       nan,
        2.225e+04]])

### 15. Use the <i> skip_header </i> and <i> usecols </i> parameters to only take the numerical data from the file. Then, let's see how the inputs change if we alter the datatype argument to:

    A) The default (not specify it)
    B) 32-bit integers (np.int32)
    C) 32-bit floats (np.float32)
    D) 64-bit complex numbers (np.complex64)
    E) Unicode (np.unicode)
    F) Objects (np.object)
    G) None

In [44]:
lending_co_total = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                 delimiter = ",", 
                                 skip_header = 1, 
                                 usecols = (0,-1),
                              # dtype = np.int32,     # B)
                              # dtype = np.float32,   # C)
                              # dtype = np.complex64, # D)
                              # dtype = np.unicode,   # E)
                              # dtype = np.objects,   # F)
                              # dype = None           # G)
                                )
lending_co_total

array([[1.0000e+00, 1.6600e+04],
       [2.0000e+00, 1.6600e+04],
       [3.0000e+00, 1.5600e+04],
       [4.0000e+00, 1.6600e+04],
       [5.0000e+00, 2.0250e+04],
       [6.0000e+00,        nan],
       [7.0000e+00, 2.0250e+04],
       [8.0000e+00, 1.6600e+04],
       [9.0000e+00, 2.2250e+04],
       [1.0000e+01, 2.0250e+04],
       [1.1000e+01, 1.6600e+04],
       [1.2000e+01, 2.0250e+04],
       [1.3000e+01, 1.6600e+04],
       [1.4000e+01, 2.0750e+04],
       [1.5000e+01, 2.2250e+04],
       [1.6000e+01, 1.6600e+04],
       [1.7000e+01, 2.2250e+04],
       [1.8000e+01, 1.6600e+04],
       [1.9000e+01, 1.6600e+04],
       [2.0000e+01, 5.4625e+04],
       [2.1000e+01, 1.6600e+04],
       [2.2000e+01, 2.2250e+04],
       [2.3000e+01, 1.9250e+04],
       [2.4000e+01, 1.5600e+04],
       [2.5000e+01, 2.0250e+04],
       [2.6000e+01, 2.2250e+04],
       [2.7000e+01, 1.9250e+04],
       [2.8000e+01, 6.9225e+04],
       [2.9000e+01, 2.0250e+04],
       [3.0000e+01, 1.6600e+04],
       [3.

### 16. Setting the datatype to None means the function automatically chooses the datatype for each column of the text file, so let's see how this works for all the columns.

In [42]:
lending_co_total = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                 delimiter = ",", 
                                 skip_header = 1, 
                                 usecols = (0,-1),
                                 dtype = None)
lending_co_total

array([[    1, 16600],
       [    2, 16600],
       [    3, 15600],
       [    4, 16600],
       [    5, 20250],
       [    6,    -1],
       [    7, 20250],
       [    8, 16600],
       [    9, 22250],
       [   10, 20250],
       [   11, 16600],
       [   12, 20250],
       [   13, 16600],
       [   14, 20750],
       [   15, 22250],
       [   16, 16600],
       [   17, 22250],
       [   18, 16600],
       [   19, 16600],
       [   20, 54625],
       [   21, 16600],
       [   22, 22250],
       [   23, 19250],
       [   24, 15600],
       [   25, 20250],
       [   26, 22250],
       [   27, 19250],
       [   28, 69225],
       [   29, 20250],
       [   30, 16600],
       [   31, 16600],
       [   32, 16600],
       [   33, 19250],
       [   34, 16600],
       [   35, 19250],
       [   36, 16600],
       [   37, 16600],
       [   38, 16600],
       [   39, 15600],
       [   40, 16600],
       [   41, 16600],
       [   42, 16600],
       [   43, 19250],
       [   