# Working with Arrays

In [1]:
import numpy as np

## Slicing

In [3]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing

In [4]:
matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
matrix_A[2:]

array([], shape=(0, 3), dtype=int32)

In [15]:
matrix_A[1:]

array([[4, 5, 6]])

In [16]:
matrix_A[:-1]

array([[1, 2, 3]])

### Stepwise Slicing

### Conditional Slicing

In [17]:
matrix_C = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [20]:
matrix_C[:,0]

array([1, 3, 4])

## Dimensions and the Squeeze Function