# NumPy Fundamentals

In [1]:
import numpy as np

## Indexing

In [2]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

### Specific Values

In [4]:
array_a[1]

array([4, 5, 6])

In [5]:
array_a[0][1]

2

In [6]:
array_a[0,1]

2

### Negative Indices

## Assigning Values

In [7]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [9]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [10]:
array_a[:, 0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [11]:
list_a = [8,7,8]

array_a[0] = list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [12]:
type(array_a[0])

numpy.ndarray

In [13]:
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [14]:
array_a = 9

In [15]:
type(array_a )

int

In [17]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

## Elementwise Properties

In [18]:
array_a + 2

array([[3, 4, 5],
       [6, 7, 8]])

## Types of Data Supported by NumPy

In [19]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = "float32")
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [25]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float16)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [26]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

https://numpy.org/devdocs/reference/generated/numpy.dtype.kind.html <- <i> A link to the documentation explaining the unicode abbreviation.

## Characteristics of NumPy Functions

### Universal Functions

https://numpy.org/devdocs/reference/ufuncs.html <- <i> A link to the documentation page on Universal Functions

### Broadcasting

In [27]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [29]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [30]:
matrix_C = np.array([[1,2,3],[4,5,6]])
matrix_C

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.add(array_b, matrix_C)

array([[2, 3, 4],
       [6, 7, 8]])

### Type Casting

In [33]:
np.add(array_b, matrix_C, dtype = np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

### Running over an Axis